# SPDX-License-Identifier: MPL-2.0
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
     - dependency-name: "opensea-common"
     - dependency-name: "opensea-transport"
     - dependency-name: "opensea-operations"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
