# SPDX-License-Identifier: MPL-2.0
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
     - dependency-name: "subprojects/opensea-common"
     - dependency-name: "subprojects/opensea-transport"
     - dependency-name: "subprojects/opensea-operations"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
