# SPDX-License-Identifier: MPL-2.0
#
# Do NOT modify or remove this copyright and license
#
# Copyright (c) 2026-2026 Seagate Technology LLC and/or its Affiliates, All Rights Reserved
#
# This software is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# ******************************************************************************************
#
# \file library.mk
# \brief Library build rules with proper dependency chains for parallel builds

#===============================================================================
# Library Source Files
#===============================================================================

# Include source lists from subprojects (single source of truth)
include $(COMMON_DIR)/sources.mk
include $(TRANSPORT_DIR)/sources.mk
include $(OPERATIONS_DIR)/sources.mk

#===============================================================================
# Include Directories
#===============================================================================

COMMON_INCLUDES := -I$(COMMON_DIR)/include
TRANSPORT_INCLUDES := -I$(TRANSPORT_DIR)/include -I$(COMMON_DIR)/include
OPERATIONS_INCLUDES := -I$(OPERATIONS_DIR)/include -I$(TRANSPORT_DIR)/include -I$(COMMON_DIR)/include

# Add to CFLAGS per library
COMMON_CFLAGS += $(COMMON_INCLUDES)
TRANSPORT_CFLAGS += $(TRANSPORT_INCLUDES)
OPERATIONS_CFLAGS += $(OPERATIONS_INCLUDES)

#===============================================================================
# Object File Lists
#===============================================================================

COMMON_OBJS := $(addprefix $(OBJ_DIR_COMMON)/,$(COMMON_SOURCES:.c=.o))
TRANSPORT_OBJS := $(addprefix $(OBJ_DIR_TRANSPORT)/,$(TRANSPORT_SOURCES:.c=.o))
OPERATIONS_OBJS := $(addprefix $(OBJ_DIR_OPERATIONS)/,$(OPERATIONS_SOURCES:.c=.o))

# Dependency files (.d) - automatically generated by -MMD -MP
COMMON_DEPS := $(COMMON_OBJS:.o=.d)
TRANSPORT_DEPS := $(TRANSPORT_OBJS:.o=.d)
OPERATIONS_DEPS := $(OPERATIONS_OBJS:.o=.d)

#===============================================================================
# Library Targets
#===============================================================================

# Static libraries (.a)
LIBCOMMON_STATIC := $(LIB_DIR)/libopensea-common.a
LIBTRANSPORT_STATIC := $(LIB_DIR)/libopensea-transport.a
LIBOPERATIONS_STATIC := $(LIB_DIR)/libopensea-operations.a

# Shared libraries (.so) - optional
LIBCOMMON_SHARED := $(LIB_DIR)/libopensea-common.so.$(COMMON_VERSION)
LIBTRANSPORT_SHARED := $(LIB_DIR)/libopensea-transport.so.$(TRANSPORT_VERSION)
LIBOPERATIONS_SHARED := $(LIB_DIR)/libopensea-operations.so.$(OPERATIONS_VERSION)

# Default library targets (static unless BUILD_SHARED_LIBS=1)
ifeq ($(BUILD_SHARED_LIBS),1)
    LIBCOMMON := $(LIBCOMMON_SHARED)
    LIBTRANSPORT := $(LIBTRANSPORT_SHARED)
    LIBOPERATIONS := $(LIBOPERATIONS_SHARED)
else
    LIBCOMMON := $(LIBCOMMON_STATIC)
    LIBTRANSPORT := $(LIBTRANSPORT_STATIC)
    LIBOPERATIONS := $(LIBOPERATIONS_STATIC)
endif

#===============================================================================
# Build Rules with Proper Dependencies
#===============================================================================

.PHONY: opensea-common opensea-transport opensea-operations libraries

# Build all libraries
libraries: opensea-common opensea-transport opensea-operations

# opensea-common (no dependencies)
opensea-common: $(LIBCOMMON)

$(LIBCOMMON_STATIC): $(COMMON_OBJS) | $(LIB_DIR)
	$(call create_static_lib)

$(LIBCOMMON_SHARED): $(COMMON_OBJS) | $(LIB_DIR)
	$(call create_shared_lib)

# opensea-transport (depends on opensea-common)
opensea-transport: opensea-common $(LIBTRANSPORT)

$(LIBTRANSPORT_STATIC): $(TRANSPORT_OBJS) | $(LIB_DIR)
	$(call create_static_lib)

$(LIBTRANSPORT_SHARED): $(TRANSPORT_OBJS) $(LIBCOMMON) | $(LIB_DIR)
	$(LINK_MSG)
	$(Q)$(CC) -shared $(LDFLAGS) -o $@ $(TRANSPORT_OBJS) -L$(LIB_DIR) -lopensea-common $(PLATFORM_LIBS)

# opensea-operations (depends on opensea-transport and opensea-common)
opensea-operations: opensea-transport $(LIBOPERATIONS)

$(LIBOPERATIONS_STATIC): $(OPERATIONS_OBJS) | $(LIB_DIR)
	$(call create_static_lib)

$(LIBOPERATIONS_SHARED): $(OPERATIONS_OBJS) $(LIBTRANSPORT) | $(LIB_DIR)
	$(LINK_MSG)
	$(Q)$(CC) -shared $(LDFLAGS) -o $@ $(OPERATIONS_OBJS) -L$(LIB_DIR) -lopensea-transport -lopensea-common $(PLATFORM_LIBS)

#===============================================================================
# Include Dependency Files (.d files for automatic header tracking)
#===============================================================================

# When cross-compiling with MinGW, fix Windows paths in existing .d files BEFORE including them
ifeq ($(CROSS_COMPILING),1)
    $(shell find $(OBJ_DIR_COMMON) $(OBJ_DIR_TRANSPORT) $(OBJ_DIR_OPERATIONS) -name '*.d' -exec sed -i 's|C:/|/mnt/c/|g; s|D:/|/mnt/d/|g; s|E:/|/mnt/e/|g; s|\\\\|/|g' {} + 2>/dev/null || true)
endif

# .d files are post-processed during compilation to fix Windows paths on cross-compile
-include $(COMMON_DEPS)
-include $(TRANSPORT_DEPS)
-include $(OPERATIONS_DEPS)

#===============================================================================
# Export Variables
#===============================================================================

export COMMON_SOURCES
export TRANSPORT_SOURCES
export OPERATIONS_SOURCES
export COMMON_OBJS
export TRANSPORT_OBJS
export OPERATIONS_OBJS
export LIBCOMMON
export LIBTRANSPORT
export LIBOPERATIONS
