# SPDX-License-Identifier: MPL-2.0
name: Dependency Review

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          warn-on-openssf-scorecard-level: 3
