# SPDX-License-Identifier: MPL-2.0
name: MSBuild

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Make/VS.2022

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    permissions:
      contents: read
    strategy:
      matrix:
        platform: [ x64, x86 ]
        language: ['cpp']

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.1
      with:
        egress-policy: audit

    - uses: actions/checkout@v6.0.2
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Restore NuGet packages
      shell: pwsh
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      shell: pwsh
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{matrix.platform}}
