# SPDX-License-Identifier: MPL-2.0
name: CI for Vagrant Boxes

on: [push]
jobs:
  build-on-openindiana:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install Virtualbox
        run: brew install --cask virtualbox

      - name: Install Vagrant
        run: brew install --cask vagrant

      - uses: leleliu008/github-actions-vagrant@v2
        with:
          mem: 2048
          box: openindiana/hipster
          run: |
            run sudo pkg_add meson ninja gcc clang make
            
            run meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
            run meson install -C build
