# SPDX-License-Identifier: MPL-2.0
name: CI for Vagrant Boxes

on: [push]
jobs:
  build-on-openindiana:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install Virtualbox
        run: brew install --cask virtualbox

      - name: Install Vagrant
        run: brew install --cask vagrant

      - uses: vonericsen/github-actions-vagrant@main
        with:
          mem: 2048
          timeout: 600
          box: openindiana/hipster
          sync-type: rsync-auto
          run: |
            run sudo pkg update
            run sudo pkg install -y meson
            
            run meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
            run meson install -C build

  build-on-freebsd:
    runs-on: macos-13
    strategy:
      fail-fast: false # so that if one config fails, other won't be cancelled automatically
      matrix:
        config:
            - {
                name: "FreeBSD 14",
                box: generic/freebsd14
              }
            - {
                name: "FreeBSD 13",
                box: generic/freebsd13
              }
            - {
                name: "Hardened BSD",
                box: generic/hardenedbsd
              }
            # - {
            #     name: "DragonFly BSD",
            #     box: generic/dragonflybsd
            #   }
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install Virtualbox
        run: brew install --cask virtualbox

      - name: Install Vagrant
        run: brew install --cask vagrant

      - uses: vonericsen/github-actions-vagrant@main
        with:
          mem: 2048
          box: ${{ matrix.config.box }}
          run: |
            run pkg update
            run pkg install -y meson
            
            run meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
            run meson install -C build
