# SPDX-License-Identifier: MPL-2.0
name: CI for Vagrant Boxes

on: [push]
jobs:
  build-on-openindiana:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install Virtualbox
        run: brew install --cask virtualbox

      - name: Install Vagrant
        run: brew install --cask vagrant

      - uses: leleliu008/github-actions-vagrant@v2
        with:
          mem: 2048
          box: Toasterson/omnitribblix
          run: |
            run sudo zap refresh
            run sudo zap install-overlay develop
            run sudo zap list-overlays
            run sudo zap install-overlay meson
            run sudo zap install-overlay ninja
            
            run meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
            run meson install -C build

  build-on-freebsd:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install Virtualbox
        run: brew install --cask virtualbox

      - name: Install Vagrant
        run: brew install --cask vagrant

      - uses: leleliu008/github-actions-vagrant@v2
        with:
          mem: 2048
          box: generic/freebsd14
          run: |
            run pkg update
            run pkg install -y meson clang
            
            run meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
            run meson install -C build
