name: Build
on: [push]
jobs:
  build-on-openindiana:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: openindiana/hipster
          run: |
            run sudo pkg_add meson ninja gcc clang make
            
            run meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
            run meson install -C build
