# SPDX-License-Identifier: MPL-2.0
name: VMActions CI for meson build

on: [push]

jobs:
  omnios:
    runs-on: ubuntu-latest
    name: Build openSeaChest for omnios
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build openSeaChest for OmniOS
      id: omni
      uses: vmactions/omnios-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install socat

        run: |
          pkg update
          pkg install bison build-essential flex ninja pkg-config

          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson
          meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
          meson install -C build

# issues with C11 annex K still need troubleshooting
#   solaris:
#     runs-on: ubuntu-latest
#     name: Build openSeaChest for Solaris
#     steps:
#     - uses: actions/checkout@v4
#       with:
#         submodules: recursive
#     - name: Build openSeaChest for Solaris
#       id: sol
#       uses: vmactions/solaris-vm@v1
#       with:
#         release: "11.4-gcc"
#         usesh: true
#         prepare: |
#           pkgutil -y -i socat

#         run: |
#           pkg update
#           pkg install developer/build/meson

#           meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
#           meson install -C build

  freebsd:
    runs-on: ubuntu-latest
    name: Build openSeaChest for FreeBSD
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build openSeaChest for  FreeBSD
      id: freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y curl

        run: |
          pkg update
          pkg install -y meson

          meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
          meson install -C build

#NOTE: dragonfly does not support ATA-CAM like FreeBSD, so need some ifdef's around that code -TJE
#   dragonflybsd:
#     runs-on: ubuntu-latest
#     name: Build openSeaChest for DragonflyBSD
#     steps:
#     - uses: actions/checkout@v4
#       with:
#         submodules: recursive
#     - name: Build openSeaChest for  DragonflyBSD
#       id: dragonfly
#       uses: vmactions/dragonflybsd-vm@v1
#       with:
#         usesh: true
#         prepare: |
#           pkg install -y socat

#         run: |
#           pkg update
#           pkg install -y meson

#           meson setup build -Dprefix=/ -Dmandir=/man -Dbindir=/ --buildtype=release
#           meson install -C build
